---
- name: install postgres
  sudo: yes
  action: apt name={{item}}
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: create project database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{db_name}}
