---
- name: clone nvm
  sudo: yes
  sudo_user: "{{user_name}}"
  git: >-
    repo=https://github.com/creationix/nvm.git
    dest=~/.nvm
    update=no
    accept_hostkey=yes

- name: source nvm in .profile
  sudo: yes
  sudo_user: "{{user_name}}"
  lineinfile: >-
    dest=~/.profile
    line=". ~/.nvm/nvm.sh"
