---
- name: clone nvm
  sudo: yes
  sudo_user: "{{user_name}}"
  git: >-
    repo=https://github.com/creationix/nvm.git
    dest=~/.nvm
    update=no
    accept_hostkey=yes

- name: source nvm in .profile
  sudo: yes
  sudo_user: "{{user_name}}"
  lineinfile: >-
    dest=~/.profile
    line=". ~/.nvm/nvm.sh"

- name: install node version {{node_version}}
  command: sudo -iu {{user_name}} nvm install {{node_version}}
  register: nvm_install_result
  changed_when: nvm_install_result.stdout.find('is already installed.') != -1
